# Generated by Django 4.1.7 on 2023-03-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comic_vine_id', models.IntegerField()),
                ('series_title', models.CharField(max_length=150)),
                ('issue_number', models.IntegerField()),
                ('issue_name', models.CharField(max_length=150)),
            ],
        ),
    ]
